---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: bundle exec rake spec SPEC_OPTS='--format documentation'
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
  global:
    - PUBLISHER_LOGIN=puppetlabs
    - secure: |-
        lu5HdlfUjkvG3q5AE/Hm7RDh6vmtPaMEjYpWT7rHRT7L6jiEIVr8cIZmPW41V9TqGO+SfAB
        B5J8VRWFHZQQHhz4sTs3BFRV3FLIjyCFF0GyE9oNEx3tghgDi5dpGAbcrti3FYR8r2drQNU
        WSYlWXYSNNIlA7xJIvgjoqRmSm3s8=
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.2.0"
notifications:
  email: false
